### ISSUE TITLE
GLD Changelist

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#11]

**Comment by martinmadaras** [comment]
1) gldAddModel
2)gldAddModelEdges
3)gldAddModelData
- vsetko ostane po starom
- pridavanie vertexovych atribut
  teraz pouzivam gldAddModelSkinningData("model skinning", indicesBO, weightsBO);

chceme to vseobecne gldAddModelVertexAttrib("model skinning", idAtributu, idBUffra)

**Comment by martinmadaras** [comment]
ftlab.sk/~mado/GLD_lib.zip

**Comment by auxilius** [comment]
Funkcia <code>gldAddModelVertexAttrib</code> nastavi buffer s attributmy. Jednotlive volania sa vzdy skladaju za seba a nepremazavaju sa.

<pre>bool gldAddModelVertexAttrib(
    std::string <b>caption</b>, <i>// caption modelu pre ktory to plati</i>
    GLuint <b>location</b>, <i>// idcko atributu cez ktore sa bude v shadery pristupovat</i>
    GLint <b>size</b>, <i>// pocet komponentov dat (od 1 po 4)</i>
    GLenum <b>type</b>, <i>// typ: GL_INT, FL_FLOAT...</i>
    GLuint <b>buffer</b> <i>// id bufferu v ktorom si data ulozene</i>
);</pre>
