### ISSUE TITLE
Dataset: Process new dataset no. 8

### ISSUE THREAD

**Issue by auxilius** [SkeletonExtensions/SkeletonExtensions#114]

**Comment by auxilius** [comment]
Mado, akym sposobom to bolo nahravane? je pod tebou strasne silny tien, mam pocit ze nejake zle osvetlenie tam bolo, vobec sa to neda pouzit

**Comment by martinmadaras** [comment]
podla mna boli svetelne podmienky take iste ako minule...

polovica svetiel zapnuta....

co som si ale nevsimol je ze ako natom boli okna, ci nahodou nebol zaves
odchileny...
ale asi az v pondelok to skontrolujem, skorej to nepojde...
