### ISSUE TITLE
If scaning is started second or more times, there is more ErrorMaps visualized in the renderer

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#125]

**Comment by gitmado** [comment]
- works fine if run as standalone app from Kinexact2ReleaseVersion
- and now it also works fine when started from VS as Release...
- bug occurs only sometimes...

**Comment by martinmadaras** [comment]
the problem also is that the chamfer matching fails in that case...because the image is corrupted
