### ISSUE TITLE
gldAddLine with floating point numbers doesnt work

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#15]

**Comment by martinmadaras** [comment]
gldAddLine("FPS: %i ", &fps); ide
gldAddLine("FPS: %5.2f ", &fpsD); nejde

**Comment by auxilius** [comment]
Viewer nepodporuje uplne rovnake funkcie ako printf 
- funguju kontrolne znaky ako '%f '
- ked potrebujes len na niekolko desatinnych miest tak das jednu cifru pred 'f' cize napr. '%2f' pre zaokruhlovanie na 2 desatinne miesta (ak bude cifier viac tak sa rata iba ta posledna, tj. maximalne na 9 desatinnych)
