### ISSUE TITLE
Add option to skip pose or pose timeout

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#164]

**Comment by auxilius** [comment]
Ked to teraz prave prechadzam, Tak zistujem ze si nemozeme len tak dovolit preskocit nejaku pozu, kedze z kazdej pozy ziskavame nejake konkretne dlzky. Keby sa poza preskocitla tak by nam do vypoctu chybali hodnoty a to by viedlo k nepresnej kalkulacii. 

Skor by som to riesil tak, ze by sme pozy skratka navrhli tak aby ich vedel vykonat kazdy. Pripadne este mozeme jemne znizovat prah fitnutia kym sa poza nefitne. Ale tam by zase nestali problemy ze by vypocty o to nepresnejsie, o kolko je poza ina od pozadovanej.
