### ISSUE TITLE
implement a class for mesh rendering into the framebuffer. Rendering applyes skinning based on specified pose

### ISSUE THREAD

**Issue by auxilius** [SkeletonExtensions/SkeletonExtensions#33]
input: name of file with mesh, skeleton pose for skinning, size of an output texture
output: mesh render wrapped in GLW::Texture
interface

``` cpp
MeshRenderer(string filename);
GLUint Render(shared_ptr<SN> pose_root, int size_in_pixels);
```

object of class should be able to load a mesh from specified file, apply skinning based on specified skeleton pose. the mesh is rendered into the framebuffer. Object also automatically determines proper scaling of mesh, to fit accurately into the rendered image. Resulting render will be contain white background and black mesh siluete (no lightning necessary)

**Comment by SkeletonExtensions** [comment]
Skusim replynut sem, ci to to dojde...

Preco metoda na rendering basemeshu loaduje fajl s meshom ? Vsak basemesh
sa generuje z kostry...tj poza/kostra = mesh ... iba radiusy v nodoch treba
ku kostre

**Comment by auxilius** [comment]
no lebo asi nechceme generovat pre kazdu pozu novy base mesh. Myslel som, ze len aplikujeme skinning a predom vygenerovany base mesh budeme tahat zo suboru

**Comment by misop** [comment]
respektive loadnes kostru s radiusmi -> vytvoris basemesh -> skinujes basemesh
Ale takto ako je to napisane je to vseobecnejsie ak namiesto basemeshu budes mat napriklad komplet scan cloveka
