### ISSUE TITLE
edit SN:SkeletonNode classes to use glm and smart pointers

### ISSUE THREAD

**Issue by auxilius** [SkeletonExtensions/SkeletonExtensions#35]

**Comment by misop** [comment]
ked uz robime toto nebude dobry napad rovno pridat aj inteligentne smerniky?

**Comment by auxilius** [comment]
jj urcite ano

**Comment by SkeletonExtensions** [comment]
Toto asi platí aj všeobecne pre všetok kód... Snažte sa používať
inteligentné smerniky a najnovšiu Č++...ale v tom skeleton node určite

**Comment by misop** [comment]
este mi napadli 2 veci:
1/ mozno viete, ale pre istotu v novom C++ je auto co si samo odvodi typ. To sa moze hodit ked pisete for each loop nech vyzera krajsie -> for (auto &ptr : vector) {...}
2/ mozno by sa hodilo porozmyslat nad niecim co aplikuje nejaku metodu / funkciu rekurzivne na celu kostru. Tato operacia je super casta a pride mi to ako dost blbost stale copy&pastit ten isty kod

**Comment by auxilius** [comment]
1/ voci tomu auto som mierne skepticky... ked prechadzas nejaky starsi kod tak niekedy pokial by nebolo jasne o aky druh vektoru sa jedna podla nazvu, da sa jeho obsah zistit z prave zadaneho typu elementu, ak tam ale bude len auto tak to nevies. Akoze podla mna je to dobra vec, ale treba to pouzivat len ked je naozaj prehladny cely kod :) Ale asi som za :D

2/ to by sa dost hodilo, mat nejaku taku funkciu. Na vstupe dostane kostru a funkciu a vykona ju  pre kazdy node, moze byt :) dal by som to priamo do SkeletonNode.h

**Comment by misop** [comment]
chapem co myslis. Ale idea je ze teraz ked vymenis raw sa smart pointer odpalis vsetky funkcie co pouzivaju SkeletonNode lebo sa zmeni typ. Keby sme mali auto tak by funogvali, lebo smart pointer overloaduje operator ->

**Comment by auxilius** [comment]
aha, tak to mi nenapadlo, na to je to dost dobre veru...

**Comment by GrEEman** [comment]
znie to fajn, skusim to zacat poutzivat.. btw je padnuty git server ? nejde
mi pullovat

**Comment by martinmadaras** [comment]
hej, v sobotu vypadol cely ftlab...snad sa to v pondelok rozbeha...
