### ISSUE TITLE
Implement shader support for each mesh rendering frame into gld

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#4]

**Comment by auxilius** [comment]
A teraz vazna otazka... Ma sa do libky posielat nazov_suboru, druh_shaderu, atd..? Nebolo by lepsie poslat iba id skompilovaneho shaderu?

**Comment by SkeletonExtensions** [comment]
dobra otazka...velmi dobra :)
neviem...ale asi ano, asi to bude lepsie...ale sprav aj nejaky kod ktory
loadne textak a vytvori ten shader, nech to nemusim potom znovu robit...aj
tak to budes potrebovat na testovanie...mozes ten kod daj do tej libky
zatial, ze budu 2 moznosti...ze pushnes mu tam IDcko shadre na vstupe,
alebo nazov fajlu, ze pojde aj ja...to znie fajn, co si o tom myslis ?

2014-11-02 23:06 GMT+01:00 auxilius notifications@github.com:

**Comment by auxilius** [comment]
dobre, takze to spravim tak, ze sa primarne bude posielat idcko shaderu (alebo programu?) a potom bude nadstavbova funkcia ktora bude vediet nacitat shader zo suboru a hned ho skompilovat a priradit.

**Comment by martinmadaras** [comment]
Ok sprav tak
