### ISSUE TITLE
General - make DLLs used in release, working from subfolder of application (there are too many dlls, which messes up the application root folder)

### ISSUE THREAD

**Issue by GrEEman** [SkeletonExtensions/SkeletonExtensions#47]

**Comment by auxilius** [comment]
nerozumiem co tym myslis, skus trochu rozpisat co sa deje :D

**Comment by GrEEman** [comment]
mam pocit ze dneska hovorim uplne inou recou nez ty :D ide iba o to ze je tam na mraky dllok a kym tam medzi nimi najdes to execko co chces spustit tak zosedivies, tak by mohli byt v nejakom subfoldri napriklad bin

**Comment by martinmadaras** [comment]
hej o tom sme sa bavili s adamom v piatok...

DLLka budeme mat vo foldery, lib/dll ... ked sa budu pustat projekty z VS,
tak sa nastavi cesta k DLLkam...

a ked budeme robit release verziu, tak sa DLLka nakopiruju do adresara, ale
az pre final release verziu ktora pojde von

2016-04-23 19:45 GMT+02:00 GrEEman notifications@github.com:

**Comment by GrEEman** [comment]
no o to nejde, o tom viem... ja som mal na mysli praveze az tu release fazu ked sa tam uz nakopiruju.. Proste ked Alimu uz odovzdas vysledok aby tam nemusel execko hladat medzi 12timi dllkami ci kolko ich tam je teraz

**Comment by martinmadaras** [comment]
Tak final verzia by mala vyzerat tak, ze isntalator nakopiruje DLLka do
windows/system32

A potom je to v system path a v tom foldery s exe uz nemusia tie DLL byt

**Comment by GrEEman** [comment]
a to sa takto bezne robi ? lebo asi vacsina aplikacii ktore som kedy instaloval tak mali dllka niekde vo svojom folderi.. lebo potom pri uninstalle by si nevedel ci ich mozes zo system pathu vymazat, ci ich nahodou nepouziva aj nejaka ina aplikacia

**Comment by auxilius** [comment]
no neviem presne ako sa to robi a ci sa to da, ale ak nejdeme riesenie tak som za, bude to prehladnejsie

**Comment by GrEEman** [comment]
tak dat sa to nejako predsa musi :D akoze teraz sa tym zatial nemusime moc zaoberat, moze to ostat iba v ideas, mna to iba tak napadlo tak som to tam dal aby som na to nezabudol :)
