### ISSUE TITLE
Solve std containers debugging problem

### ISSUE THREAD

**Issue by GrEEman** [SkeletonExtensions/SkeletonExtensions#50]
when debugging it is not possible to see what is inside of std containers (vectors, strings, etc..)

**Comment by auxilius** [comment]
mam pocit, ze v tomto nemame moc moznosti keze Microsoft prestal podporovat c++ formulare. Podla mna mozeme spravit nasledujuce:

a) prejst na starsie VS, napr povodne 2012 kde to bolo este podporovane, bol by to vsak krok vzad
b) pouzit pre spravu okna GLFW, a najst nejaku libku pre UI fungujuce cez openGL
c) prejst na C#, podporovany v VS2015 a vzdat sa vsetkeho co mame :D

Ak vam napada este nieco, alebo najdete riesenie ako rozbehat c++ win formular v 2015 bez \crt tak sup sem s tym

**Comment by martinmadaras** [comment]
Dá sa rozbehat form v 2015... Nejde to priamo že vybrať si z ponuky, je to
tam schované... Ale da sa to, su nato návody, videl som ich niekde

**Comment by auxilius** [comment]
form ide rozbehat, ale nie je podporaovany.
Skus potom teda tie navody najst, ja to dost neprakticke teraz

**Comment by martinmadaras** [comment]
Mozno bude treba spraviť form v 2012 a ten použiť v 2015... Zajtra keď sa
vratim z sccg tak to pozriem
On Apr 28, 2016 14:08, "auxilius" notifications@github.com wrote:

form ide rozbehat, ale nie je podporaovany.
Skus potom teda tie navody najst, ja to dost neprakticke teraz
