### ISSUE TITLE
Recompile OpenCV library with crt setting enabled

### ISSUE THREAD

**Issue by auxilius** [SkeletonExtensions/SkeletonExtensions#53]

**Comment by SkeletonExtensions** [comment]
Toto nieje to co som už raz buildoval?

**Comment by auxilius** [comment]
jj, je, ale potom si to vymazal zo servera v novom gitku to uz nie je. Potrebujeme to vyskusat lebo mame podozrenie ze nam to robi nejake problemy

**Comment by martinmadaras** [comment]
added to libraries.svn -> crt subfolder in opencv lib
