### ISSUE TITLE
Implement basic skinning shader that transform only vertices

### ISSUE THREAD

**Issue by GrEEman** [SkeletonExtensions/SkeletonExtensions#6]

**Comment by GrEEman** [comment]
Shader pushnuty, nestihol som ho zatial otestovat, skompilovat ale isiel.

**Comment by martinmadaras** [comment]
uniform vec3 bones[4] -> vo vec3 sa asi neda udrzat rotacia ? bud potrebujes vec4 ked drzis rotaciu ako quaternion, alebo mat4 na vseobecnu maticu transformacie

**Comment by GrEEman** [comment]
pushnuta nova verzia
