### ISSUE TITLE
Change system of color data storring in GLD ... use OpenGL buffer instead of pointer to values

### ISSUE THREAD

**Issue by martinmadaras** [SkeletonExtensions/SkeletonExtensions#7]

**Comment by auxilius** [comment]
cez pole to nevyhovuje? mam ich cerpat uplne z noveho buffera alebo pouzivat napr alfa kanal z bufferu vertexov? (aj ked neviem ci by som to tak vedel :D)

**Comment by SkeletonExtensions** [comment]
mohol by si to na uvod spravit tak, aby si tam mohol davat aj buder, aj
takto pole...potom sa rozhodneme ci podporu pol dame depricated

ide o tu vizualizaciu wkinning vah, aby tam chalani nemuseli drzat tie
polia...aby stacilo spravit buffer na gpu a ten ti podstrcit

2014-11-04 20:49 GMT+01:00 auxilius notifications@github.com:

**Comment by Michalzr** [comment]
rozpraval som sa o tom s adamom a ze ked ten jeho debugger vlastne naschval funguje tak ze on si neodklada ziadne informacie tak to upravim radsej ja ten vizualizer.

uz to mam skoro spravene, este v piatok alebo tak dorobim, ze ta struktura si bude pekne pametat vsetky udaje na vizualizaciu (2 buffre s vrcholmi(kostra a model), 1 s hranami kostry a 7 poli s farbami) a ked tu strukturu znicis tak aj tie buffre a pointre sa vymazu.

Potom sa ta ta struktura vizualizacie bude pouzivat tak, ze bude pocas celej vizualizacie musiet existovat. A dam tam moznost prepisat skeletona a model, kde sa to vsetko prepise, tym padom tu strukturu bude stacit vytvorit naozaj len raz a pri skonceni vizualizacie vymazat.

**Comment by martinmadaras** [comment]
ok

2014-11-06 18:11 GMT+01:00 Michalzr notifications@github.com:
