### ISSUE TITLE
Move function for cv::Mat conversion to glw::Texture object from CVE_lib to GLW_lib

### ISSUE THREAD

**Issue by GrEEman** [SkeletonExtensions/SkeletonExtensions#88]
move it to glw, so glw::texutre can be created from cv::mat, maybe with some opencv define, so it can be use without opencv

**Comment by auxilius** [comment]
My opinion:
It would need defining/undefining opencv define for each library build.
Overaly, from using perspective it would be more time consuming, then it is now.

**Comment by GrEEman** [comment]
ok i see the point
